// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xin_out.h"

extern XIn_out_Config XIn_out_ConfigTable[];

XIn_out_Config *XIn_out_LookupConfig(u16 DeviceId) {
	XIn_out_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XIN_OUT_NUM_INSTANCES; Index++) {
		if (XIn_out_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XIn_out_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XIn_out_Initialize(XIn_out *InstancePtr, u16 DeviceId) {
	XIn_out_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XIn_out_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XIn_out_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

